[profile.default]
solc = "0.8.30"
auto_detect_solc = false
auto_detect_remappings = false
bytecode_hash = "none"
optimizer_runs = 1
optimizer = true

sparse_mode = true

src = 'src'
via_ir = true
ffi = true
fs_permissions = [
  { access = "read", path = "./script" },
  { access = "write", path = "./deployments" },
  { access = "read", path = "./artifacts" }
]
verbosity = 3
evm_version = "cancun"
gas_limit = "300000000"

out = 'out'
test = 'test/'
cache_path = 'cache/foundry'

libs = ["lib"]

remappings = [
  # forge-std tests
  "ds-test/=lib/forge-std/lib/ds-test/",
  "forge-std/=lib/forge-std/src/",
  # OpenZeppelin contracts
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  # Doppler contracts
  "doppler/=src/interfaces/external/doppler/",
  # LayerZero OFT contracts
  "@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
  # LayerZero Protocol v2 contracts
  "@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  # LayerZero MessageLib v2 contracts
  "@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/",
  # Solidity bytes utils for LayerZero
  "solidity-bytes-utils/=lib/solidity-bytes-utils/",
  # Chainlink contracts for price feeds
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

# Specify include paths to control which directories are searched for imports
include_paths = [
  "src",
  "lib/forge-std/src"
]

ignored_paths = [
  # Ignore the top-level OZ copy to ensure only one version is compiled
  "lib/openzeppelin-contracts"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
unichainSepolia = "${UNICHAIN_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[profile.default.fuzz]
runs = 1000
seed = "0x4444"

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = true
optimizer_runs = 1
fuzz.runs = 100

[profile.deploy]
solc = "0.8.30"
optimizer = true
optimizer_runs = 20000
via_ir = true
bytecode_hash = "none"
