#!/bin/sh

WORDS=0
CHARACTERS=0
LINES=0

echo
git ls-files | xargs wc -c
echo

FILES=$(git ls-files)
ARRAY=${FILES%$'\n'*}
for FILE in $ARRAY
do
    if [[ $FILE != solc* ]] ;
    then
        LINE_COUNT=$(wc -l < $FILE)
        LINES=$(($LINES+$(($LINE_COUNT))))
        WORD_COUNT=$(wc -w < $FILE)
        WORDS=$(($WORDS+$(($WORD_COUNT))))
        CHARACTER_COUNT=$(wc -m < $FILE)
        CHARACTERS=$(($CHARACTERS+$(($CHARACTER_COUNT))))
    fi
done

echo
echo a total of
echo $LINES lines
echo $WORDS words
echo $CHARACTERS characters
echo were generated by this project
echo this does not include any external code or libraries
echo

exit